### ISSUE TITLE
Crash application - NullPointer in obfuscated code

### ISSUE THREAD

**Issue by SylvainGourdaut** [Tealium/tealium-android#31]
Tealium version: 5.2.0

Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'com.tealium.internal.b com.tealium.internal.b.c.e' on a null object reference

Stack trace:
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'com.tealium.internal.b com.tealium.internal.b.c.e' on a null object reference
       at com.tealium.internal.b.c.c(Unknown Source)
       at com.tealium.internal.b.c$2.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

Seems to appear only on : 
Device : Archos
OS : Android 5

5 Crashes in the last 2 days.

**Comment by craigrouse** [comment]
@SylvainGourdaut sorry for the delay. Have you seen any more instances of this, and does it still appear to only happen on Archos devices? Thanks.

**Comment by tamayok** [comment]
@SylvainGourdaut any updates on this? Please let us know if you continue to have issues. Alternatively, please email the support team - support@tealium.com- for more help.

**Comment by tamayok** [comment]
@SylvainGourdaut Are you still seeing this issues? We've made some updates to the library since you submitted this. If possible, please update to the latest and let us know if the issue persists.

**Comment by craigrouse** [comment]
Closing issue due to inactivity.
