### ISSUE TITLE
java.lang.IllegalAccessException

### ISSUE THREAD

**Issue by carlosgorillalogic** [Tealium/tealium-android#96]
Device: Google Pixel 4a, Android 13.

When enable [detectIncorrectContextUse](https://developer.android.com/reference/android/os/StrictMode.VmPolicy.Builder#detectIncorrectContextUse()), I got the following error:

Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.jdsports.app.App@837c523 The API:ViewConfiguration needs a proper configuration. Use UI contexts such as an activity or a context created via createWindowContext(Display, int, Bundle) or  createConfigurationContext(Configuration) with a proper configuration.
                                                             java.lang.IllegalAccessException: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:<>.App@837c523
                                                             	at android.os.StrictMode.assertConfigurationContext(StrictMode.java:2295)
                                                             	at android.view.ViewConfiguration.get(ViewConfiguration.java:526)
                                                             	at android.view.View.<init>(View.java:5366)
                                                             	at android.view.View.<init>(View.java:5511)
                                                             	at android.view.ViewGroup.<init>(ViewGroup.java:703)
                                                             	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
                                                             	at android.webkit.WebView.<init>(WebView.java:421)
                                                             	at android.webkit.WebView.<init>(WebView.java:363)
                                                             	at android.webkit.WebView.<init>(WebView.java:345)
                                                             	at android.webkit.WebView.<init>(WebView.java:332)
                                                             	at android.webkit.WebView.<init>(WebView.java:322)
                                                             	at com.tealium.internal.dispatcher.WebViewDispatcher$b.run(WebViewDispatcher.java:5)
                                                             	at android.os.Handler.handleCallback(Handler.java:942)
                                                             	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                             	at android.os.Looper.loopOnce(Looper.java:201)
                                                             	at android.os.Looper.loop(Looper.java:288)
                                                             	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                             	at java.lang.reflect.Method.invoke(Native Method)
                                                             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                             	
It seems like `Tealium.Config.create` does not like the application context.

**Comment by mrgonzalez-applaudo** [comment]
I'm getting the exact same error on 1.7.0, causing loads of ANRs on Android 14 and 15 devices, any workaround?
```
Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.volaris.VolarisApp@247df49 The API:ViewConfiguration needs a proper configuration. Use UI contexts such as an activity or a context created via createWindowContext(Display, int, Bundle) or  createConfigurationContext(Configuration) with a proper configuration.
java.lang.IllegalAccessException: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.volaris.VolarisApp@247df49
	at android.os.StrictMode.assertConfigurationContext(StrictMode.java:2352)
	at android.view.ViewConfiguration.get(ViewConfiguration.java:604)
	at android.view.View.<init>(View.java:5820)
	at android.view.View.<init>(View.java:5951)
	at android.view.ViewGroup.<init>(ViewGroup.java:703)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:422)
	at android.webkit.WebView.<init>(WebView.java:364)
	at android.webkit.WebView.<init>(WebView.java:346)
	at android.webkit.WebView.<init>(WebView.java:333)
	at android.webkit.WebView.<init>(WebView.java:323)
	at com.tealium.tagmanagementdispatcher.d.invoke(SourceFile:1)
	at com.tealium.tagmanagementdispatcher.e$b.invokeSuspend(SourceFile:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

```
